"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xv4hp)#4uy_+3i1_5u1-h^j91!ujx+ij%(e#35q&qrg5$(7f-('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        "ALLOWED_HOSTS",
        "localhost,127.0.0.1,bot.sohag.com.bd,15.204.67.249,ai.sohag.com.bd",
    ).split(",")
    if h.strip()
]

# Meta callback: this Django app serves it at MESSENGER_WEBHOOK_PATH (default /api/webhook/).
# Option A: set full URL for Settings page display — e.g. https://bot.sohag.com.bd/api/webhook
MESSENGER_WEBHOOK_PUBLIC_URL = os.environ.get("MESSENGER_WEBHOOK_PUBLIC_URL", "").strip()
# Option B: or set base only; display URL = PUBLIC_WEBHOOK_BASE + MESSENGER_WEBHOOK_PATH
PUBLIC_WEBHOOK_BASE = os.environ.get(
    "PUBLIC_WEBHOOK_BASE",
    "https://bot.sohag.com.bd",
).rstrip("/")
_raw_path = os.environ.get("MESSENGER_WEBHOOK_PATH", "/api/webhook").strip() or "/api/webhook"
if not _raw_path.startswith("/"):
    _raw_path = "/" + _raw_path
MESSENGER_WEBHOOK_PATH = _raw_path if _raw_path.endswith("/") else _raw_path + "/"

# HTTPS POST (forms, admin) must list the site origin(s), scheme included (Django 4+).
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]
for _origin in (
    PUBLIC_WEBHOOK_BASE,
    "http://127.0.0.1:8000",
    "http://localhost:8000",
):
    if _origin and _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)

MESSENGER_VERIFY_TOKEN = os.environ.get("MESSENGER_VERIFY_TOKEN", "")
MESSENGER_PAGE_ACCESS_TOKEN = os.environ.get("MESSENGER_PAGE_ACCESS_TOKEN", "")
MESSENGER_APP_SECRET = os.environ.get("MESSENGER_APP_SECRET", "")
# Graph version for Messenger send + user profile (e.g. v19.0 if v21 misbehaves for your app).
MESSENGER_GRAPH_API_VERSION = (
    os.environ.get("MESSENGER_GRAPH_API_VERSION", "v21.0").strip() or "v21.0"
)

# API routes under /api/* (except /api/webhook): max requests per minute per IP. Set 0 to disable.
try:
    API_RATE_LIMIT_PER_MINUTE = int(os.environ.get("API_RATE_LIMIT_PER_MINUTE", "15"))
except ValueError:
    API_RATE_LIMIT_PER_MINUTE = 15

# Staff inbox UI polls many URLs; separate bucket so it does not share the strict default above.
try:
    API_INBOX_RATE_LIMIT_PER_MINUTE = int(
        os.environ.get("API_INBOX_RATE_LIMIT_PER_MINUTE", "300")
    )
except ValueError:
    API_INBOX_RATE_LIMIT_PER_MINUTE = 300

# Inbox sidebar: only the N most recently updated threads (not full history).
try:
    INBOX_RECENT_CONVERSATIONS_LIMIT = int(
        os.environ.get("INBOX_RECENT_CONVERSATIONS_LIMIT", "80")
    )
except ValueError:
    INBOX_RECENT_CONVERSATIONS_LIMIT = 80
INBOX_RECENT_CONVERSATIONS_LIMIT = max(10, min(INBOX_RECENT_CONVERSATIONS_LIMIT, 500))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shopchat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'shopchat.middleware.ApiRateLimitMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # Wait longer when another thread holds the write lock (webhook + admin, etc.).
        'OPTIONS': {
            'timeout': 30,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


def _env_bool(key: str, default: bool) -> bool:
    v = os.environ.get(key, "")
    if v == "":
        return default
    return v.strip().lower() not in ("0", "false", "no", "off")


def _env_int(key: str, default: int) -> int:
    try:
        return int(os.environ.get(key, str(default)))
    except ValueError:
        return default


def _env_float(key: str, default: float) -> float:
    try:
        return float(os.environ.get(key, str(default)))
    except ValueError:
        return default


# Hard caps on outbound Gemini calls per UTC minute (free-tier margin). When full, the app waits
# until the next minute (up to GEMINI_RL_MAX_WAIT_SEC). Process-wide: all keys share counters
# (correct when keys are the same Google project). Separate counter per chat model id.
GEMINI_RATE_LIMIT_ENABLED = _env_bool("GEMINI_RATE_LIMIT_ENABLED", True)
GEMINI_RL_EMBEDDING_PER_MINUTE = _env_int("GEMINI_RL_EMBEDDING_PER_MINUTE", 25)
GEMINI_RL_CHAT_PER_MODEL_PER_MINUTE = _env_int("GEMINI_RL_CHAT_PER_MODEL_PER_MINUTE", 10)
GEMINI_RL_MAX_WAIT_SEC = _env_float("GEMINI_RL_MAX_WAIT_SEC", 180.0)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "shopchat",
    }
}

# Console logging for shopchat (override with SHOPCHAT_LOG_LEVEL=DEBUG|INFO|WARNING)
_SHOPCHAT_LOG_LEVEL = os.environ.get(
    "SHOPCHAT_LOG_LEVEL",
    "DEBUG" if DEBUG else "INFO",
).upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "shopchat": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
            "datefmt": "%H:%M:%S",
        },
    },
    "handlers": {
        "shopchat_console": {
            "class": "logging.StreamHandler",
            "formatter": "shopchat",
        },
    },
    "loggers": {
        "shopchat": {
            "handlers": ["shopchat_console"],
            "level": _SHOPCHAT_LOG_LEVEL,
            "propagate": False,
        },
    },
}
