# Generated by Django 6.0.4 on 2026-04-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default='You are a knowledgeable shop assistant. Use the retrieved product information when it helps answer the customer. Be concise and helpful.')),
                ('gemini_chat_model', models.CharField(default='gemini-2.0-flash', help_text='Model id for replies (e.g. gemini-2.0-flash).', max_length=128)),
                ('gemini_embedding_model', models.CharField(default='gemini-embedding-2-preview', help_text='Multimodal embedding model for product and user images.', max_length=128)),
                ('embedding_output_dimensionality', models.PositiveIntegerField(default=768, help_text='Embedding vector size (e.g. 768). Must match for cosine search.')),
                ('similarity_top_k', models.PositiveIntegerField(default=5, help_text='How many closest product images to inject into context.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App settings',
                'verbose_name_plural': 'App settings',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Optional text stored with the product (shown to the model).')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
