# Generated by Django 6.0.4 on 2026-04-16 17:42

from django.db import migrations, models


def use_gemma_for_prior_flash_default(apps, schema_editor):
    AppSettings = apps.get_model("shopchat", "AppSettings")
    AppSettings.objects.filter(pk=1, gemini_chat_model="gemini-2.0-flash").update(
        gemini_chat_model="gemma-4-31b-it"
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shopchat', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='gemini_chat_model',
            field=models.CharField(default='gemma-4-31b-it', help_text='Model id for chat replies via the Gemini API. Gemma 4 31B: gemma-4-31b-it. Gemini examples: gemini-2.0-flash, gemini-2.5-flash-preview.', max_length=128),
        ),
        migrations.RunPython(use_gemma_for_prior_flash_default, noop_reverse),
    ]
