# Generated by Django 6.0.4 on 2026-04-16 17:47

import os

from django.db import migrations, models


def seed_credential_from_env(apps, schema_editor):
    GeminiApiCredential = apps.get_model("shopchat", "GeminiApiCredential")
    if GeminiApiCredential.objects.exists():
        return
    key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not key:
        return
    GeminiApiCredential.objects.create(
        label="Imported from GEMINI_API_KEY",
        api_key=key,
        enabled=True,
        sort_order=0,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shopchat', '0003_use_gemma_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('api_key', models.CharField(max_length=512)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower runs earlier in the rotation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gemini API credential',
                'verbose_name_plural': 'Gemini API credentials',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='gemini_chat_model',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='chat_rr_seq',
            field=models.PositiveBigIntegerField(default=0, help_text='Internal counter for chat key/model round-robin.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='embed_rr_seq',
            field=models.PositiveBigIntegerField(default=0, help_text='Internal counter for embedding API key round-robin.'),
        ),
        migrations.RunPython(seed_credential_from_env, noop_reverse),
    ]
