# Generated by Django 6.0.4 on 2026-04-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopchat', '0004_gemini_credentials_round_robin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='gemini_embedding_model',
        ),
    ]
