# Generated by Django 6.0.4 on 2026-04-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopchat', '0010_geminiapicredential_auto_disable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='shopchat_ch_convers_31ce67_idx',
            old_name='shopchat_ch_convers_0f8b2f_idx',
        ),
        migrations.RenameIndex(
            model_name='geminicredentialusagebucket',
            new_name='shopchat_ge_credent_ee2725_idx',
            old_name='shopchat_ge_cred_id_2f1b0d_idx',
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='deployment_mode',
            field=models.CharField(choices=[('testing', 'Testing — inbox only (no send to Messenger)'), ('production', 'Production — send AI replies to Messenger')], default='testing', help_text='Testing: webhook still receives and stores messages, but outbound Messenger sends are skipped.', max_length=20),
        ),
    ]
