# Generated by Django 6.0.4 on 2026-04-19 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopchat', '0011_rename_shopchat_ch_convers_0f8b2f_idx_shopchat_ch_convers_31ce67_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chat_user/%Y/%m/%d/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attachments', to='shopchat.chatmessage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
